################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../fonts/fontcm12.c \
../fonts/fontcm12b.c \
../fonts/fontcm12i.c \
../fonts/fontcm14.c \
../fonts/fontcm14b.c \
../fonts/fontcm14i.c \
../fonts/fontcm16.c \
../fonts/fontcm16b.c \
../fonts/fontcm16i.c \
../fonts/fontcm18.c \
../fonts/fontcm18b.c \
../fonts/fontcm18i.c \
../fonts/fontcm20.c \
../fonts/fontcm20b.c \
../fonts/fontcm20i.c \
../fonts/fontcm22.c \
../fonts/fontcm22b.c \
../fonts/fontcm22i.c \
../fonts/fontcm24.c \
../fonts/fontcm24b.c \
../fonts/fontcm24i.c \
../fonts/fontcm26.c \
../fonts/fontcm26b.c \
../fonts/fontcm26i.c \
../fonts/fontcm28.c \
../fonts/fontcm28b.c \
../fonts/fontcm28i.c \
../fonts/fontcm30.c \
../fonts/fontcm30b.c \
../fonts/fontcm30i.c \
../fonts/fontcm32.c \
../fonts/fontcm32b.c \
../fonts/fontcm32i.c \
../fonts/fontcm34.c \
../fonts/fontcm34b.c \
../fonts/fontcm34i.c \
../fonts/fontcm36.c \
../fonts/fontcm36b.c \
../fonts/fontcm36i.c \
../fonts/fontcm38.c \
../fonts/fontcm38b.c \
../fonts/fontcm38i.c \
../fonts/fontcm40.c \
../fonts/fontcm40b.c \
../fonts/fontcm40i.c \
../fonts/fontcm42.c \
../fonts/fontcm42b.c \
../fonts/fontcm42i.c \
../fonts/fontcm44.c \
../fonts/fontcm44b.c \
../fonts/fontcm44i.c \
../fonts/fontcm46.c \
../fonts/fontcm46b.c \
../fonts/fontcm46i.c \
../fonts/fontcm48.c \
../fonts/fontcm48b.c \
../fonts/fontcm48i.c \
../fonts/fontcmsc12.c \
../fonts/fontcmsc14.c \
../fonts/fontcmsc16.c \
../fonts/fontcmsc18.c \
../fonts/fontcmsc20.c \
../fonts/fontcmsc22.c \
../fonts/fontcmsc24.c \
../fonts/fontcmsc26.c \
../fonts/fontcmsc28.c \
../fonts/fontcmsc30.c \
../fonts/fontcmsc32.c \
../fonts/fontcmsc34.c \
../fonts/fontcmsc36.c \
../fonts/fontcmsc38.c \
../fonts/fontcmsc40.c \
../fonts/fontcmsc42.c \
../fonts/fontcmsc44.c \
../fonts/fontcmsc46.c \
../fonts/fontcmsc48.c \
../fonts/fontcmss12.c \
../fonts/fontcmss12b.c \
../fonts/fontcmss12i.c \
../fonts/fontcmss14.c \
../fonts/fontcmss14b.c \
../fonts/fontcmss14i.c \
../fonts/fontcmss16.c \
../fonts/fontcmss16b.c \
../fonts/fontcmss16i.c \
../fonts/fontcmss18.c \
../fonts/fontcmss18b.c \
../fonts/fontcmss18i.c \
../fonts/fontcmss20.c \
../fonts/fontcmss20b.c \
../fonts/fontcmss20i.c \
../fonts/fontcmss22.c \
../fonts/fontcmss22b.c \
../fonts/fontcmss22i.c \
../fonts/fontcmss24.c \
../fonts/fontcmss24b.c \
../fonts/fontcmss24i.c \
../fonts/fontcmss26.c \
../fonts/fontcmss26b.c \
../fonts/fontcmss26i.c \
../fonts/fontcmss28.c \
../fonts/fontcmss28b.c \
../fonts/fontcmss28i.c \
../fonts/fontcmss30.c \
../fonts/fontcmss30b.c \
../fonts/fontcmss30i.c \
../fonts/fontcmss32.c \
../fonts/fontcmss32b.c \
../fonts/fontcmss32i.c \
../fonts/fontcmss34.c \
../fonts/fontcmss34b.c \
../fonts/fontcmss34i.c \
../fonts/fontcmss36.c \
../fonts/fontcmss36b.c \
../fonts/fontcmss36i.c \
../fonts/fontcmss38.c \
../fonts/fontcmss38b.c \
../fonts/fontcmss38i.c \
../fonts/fontcmss40.c \
../fonts/fontcmss40b.c \
../fonts/fontcmss40i.c \
../fonts/fontcmss42.c \
../fonts/fontcmss42b.c \
../fonts/fontcmss42i.c \
../fonts/fontcmss44.c \
../fonts/fontcmss44b.c \
../fonts/fontcmss44i.c \
../fonts/fontcmss46.c \
../fonts/fontcmss46b.c \
../fonts/fontcmss46i.c \
../fonts/fontcmss48.c \
../fonts/fontcmss48b.c \
../fonts/fontcmss48i.c \
../fonts/fontcmtt12.c \
../fonts/fontcmtt14.c \
../fonts/fontcmtt16.c \
../fonts/fontcmtt18.c \
../fonts/fontcmtt20.c \
../fonts/fontcmtt22.c \
../fonts/fontcmtt24.c \
../fonts/fontcmtt26.c \
../fonts/fontcmtt28.c \
../fonts/fontcmtt30.c \
../fonts/fontcmtt32.c \
../fonts/fontcmtt34.c \
../fonts/fontcmtt36.c \
../fonts/fontcmtt38.c \
../fonts/fontcmtt40.c \
../fonts/fontcmtt42.c \
../fonts/fontcmtt44.c \
../fonts/fontcmtt46.c \
../fonts/fontcmtt48.c \
../fonts/fontfixed6x8.c 

OBJS += \
./fonts/fontcm12.obj \
./fonts/fontcm12b.obj \
./fonts/fontcm12i.obj \
./fonts/fontcm14.obj \
./fonts/fontcm14b.obj \
./fonts/fontcm14i.obj \
./fonts/fontcm16.obj \
./fonts/fontcm16b.obj \
./fonts/fontcm16i.obj \
./fonts/fontcm18.obj \
./fonts/fontcm18b.obj \
./fonts/fontcm18i.obj \
./fonts/fontcm20.obj \
./fonts/fontcm20b.obj \
./fonts/fontcm20i.obj \
./fonts/fontcm22.obj \
./fonts/fontcm22b.obj \
./fonts/fontcm22i.obj \
./fonts/fontcm24.obj \
./fonts/fontcm24b.obj \
./fonts/fontcm24i.obj \
./fonts/fontcm26.obj \
./fonts/fontcm26b.obj \
./fonts/fontcm26i.obj \
./fonts/fontcm28.obj \
./fonts/fontcm28b.obj \
./fonts/fontcm28i.obj \
./fonts/fontcm30.obj \
./fonts/fontcm30b.obj \
./fonts/fontcm30i.obj \
./fonts/fontcm32.obj \
./fonts/fontcm32b.obj \
./fonts/fontcm32i.obj \
./fonts/fontcm34.obj \
./fonts/fontcm34b.obj \
./fonts/fontcm34i.obj \
./fonts/fontcm36.obj \
./fonts/fontcm36b.obj \
./fonts/fontcm36i.obj \
./fonts/fontcm38.obj \
./fonts/fontcm38b.obj \
./fonts/fontcm38i.obj \
./fonts/fontcm40.obj \
./fonts/fontcm40b.obj \
./fonts/fontcm40i.obj \
./fonts/fontcm42.obj \
./fonts/fontcm42b.obj \
./fonts/fontcm42i.obj \
./fonts/fontcm44.obj \
./fonts/fontcm44b.obj \
./fonts/fontcm44i.obj \
./fonts/fontcm46.obj \
./fonts/fontcm46b.obj \
./fonts/fontcm46i.obj \
./fonts/fontcm48.obj \
./fonts/fontcm48b.obj \
./fonts/fontcm48i.obj \
./fonts/fontcmsc12.obj \
./fonts/fontcmsc14.obj \
./fonts/fontcmsc16.obj \
./fonts/fontcmsc18.obj \
./fonts/fontcmsc20.obj \
./fonts/fontcmsc22.obj \
./fonts/fontcmsc24.obj \
./fonts/fontcmsc26.obj \
./fonts/fontcmsc28.obj \
./fonts/fontcmsc30.obj \
./fonts/fontcmsc32.obj \
./fonts/fontcmsc34.obj \
./fonts/fontcmsc36.obj \
./fonts/fontcmsc38.obj \
./fonts/fontcmsc40.obj \
./fonts/fontcmsc42.obj \
./fonts/fontcmsc44.obj \
./fonts/fontcmsc46.obj \
./fonts/fontcmsc48.obj \
./fonts/fontcmss12.obj \
./fonts/fontcmss12b.obj \
./fonts/fontcmss12i.obj \
./fonts/fontcmss14.obj \
./fonts/fontcmss14b.obj \
./fonts/fontcmss14i.obj \
./fonts/fontcmss16.obj \
./fonts/fontcmss16b.obj \
./fonts/fontcmss16i.obj \
./fonts/fontcmss18.obj \
./fonts/fontcmss18b.obj \
./fonts/fontcmss18i.obj \
./fonts/fontcmss20.obj \
./fonts/fontcmss20b.obj \
./fonts/fontcmss20i.obj \
./fonts/fontcmss22.obj \
./fonts/fontcmss22b.obj \
./fonts/fontcmss22i.obj \
./fonts/fontcmss24.obj \
./fonts/fontcmss24b.obj \
./fonts/fontcmss24i.obj \
./fonts/fontcmss26.obj \
./fonts/fontcmss26b.obj \
./fonts/fontcmss26i.obj \
./fonts/fontcmss28.obj \
./fonts/fontcmss28b.obj \
./fonts/fontcmss28i.obj \
./fonts/fontcmss30.obj \
./fonts/fontcmss30b.obj \
./fonts/fontcmss30i.obj \
./fonts/fontcmss32.obj \
./fonts/fontcmss32b.obj \
./fonts/fontcmss32i.obj \
./fonts/fontcmss34.obj \
./fonts/fontcmss34b.obj \
./fonts/fontcmss34i.obj \
./fonts/fontcmss36.obj \
./fonts/fontcmss36b.obj \
./fonts/fontcmss36i.obj \
./fonts/fontcmss38.obj \
./fonts/fontcmss38b.obj \
./fonts/fontcmss38i.obj \
./fonts/fontcmss40.obj \
./fonts/fontcmss40b.obj \
./fonts/fontcmss40i.obj \
./fonts/fontcmss42.obj \
./fonts/fontcmss42b.obj \
./fonts/fontcmss42i.obj \
./fonts/fontcmss44.obj \
./fonts/fontcmss44b.obj \
./fonts/fontcmss44i.obj \
./fonts/fontcmss46.obj \
./fonts/fontcmss46b.obj \
./fonts/fontcmss46i.obj \
./fonts/fontcmss48.obj \
./fonts/fontcmss48b.obj \
./fonts/fontcmss48i.obj \
./fonts/fontcmtt12.obj \
./fonts/fontcmtt14.obj \
./fonts/fontcmtt16.obj \
./fonts/fontcmtt18.obj \
./fonts/fontcmtt20.obj \
./fonts/fontcmtt22.obj \
./fonts/fontcmtt24.obj \
./fonts/fontcmtt26.obj \
./fonts/fontcmtt28.obj \
./fonts/fontcmtt30.obj \
./fonts/fontcmtt32.obj \
./fonts/fontcmtt34.obj \
./fonts/fontcmtt36.obj \
./fonts/fontcmtt38.obj \
./fonts/fontcmtt40.obj \
./fonts/fontcmtt42.obj \
./fonts/fontcmtt44.obj \
./fonts/fontcmtt46.obj \
./fonts/fontcmtt48.obj \
./fonts/fontfixed6x8.obj 

C_DEPS += \
./fonts/fontcm12.pp \
./fonts/fontcm12b.pp \
./fonts/fontcm12i.pp \
./fonts/fontcm14.pp \
./fonts/fontcm14b.pp \
./fonts/fontcm14i.pp \
./fonts/fontcm16.pp \
./fonts/fontcm16b.pp \
./fonts/fontcm16i.pp \
./fonts/fontcm18.pp \
./fonts/fontcm18b.pp \
./fonts/fontcm18i.pp \
./fonts/fontcm20.pp \
./fonts/fontcm20b.pp \
./fonts/fontcm20i.pp \
./fonts/fontcm22.pp \
./fonts/fontcm22b.pp \
./fonts/fontcm22i.pp \
./fonts/fontcm24.pp \
./fonts/fontcm24b.pp \
./fonts/fontcm24i.pp \
./fonts/fontcm26.pp \
./fonts/fontcm26b.pp \
./fonts/fontcm26i.pp \
./fonts/fontcm28.pp \
./fonts/fontcm28b.pp \
./fonts/fontcm28i.pp \
./fonts/fontcm30.pp \
./fonts/fontcm30b.pp \
./fonts/fontcm30i.pp \
./fonts/fontcm32.pp \
./fonts/fontcm32b.pp \
./fonts/fontcm32i.pp \
./fonts/fontcm34.pp \
./fonts/fontcm34b.pp \
./fonts/fontcm34i.pp \
./fonts/fontcm36.pp \
./fonts/fontcm36b.pp \
./fonts/fontcm36i.pp \
./fonts/fontcm38.pp \
./fonts/fontcm38b.pp \
./fonts/fontcm38i.pp \
./fonts/fontcm40.pp \
./fonts/fontcm40b.pp \
./fonts/fontcm40i.pp \
./fonts/fontcm42.pp \
./fonts/fontcm42b.pp \
./fonts/fontcm42i.pp \
./fonts/fontcm44.pp \
./fonts/fontcm44b.pp \
./fonts/fontcm44i.pp \
./fonts/fontcm46.pp \
./fonts/fontcm46b.pp \
./fonts/fontcm46i.pp \
./fonts/fontcm48.pp \
./fonts/fontcm48b.pp \
./fonts/fontcm48i.pp \
./fonts/fontcmsc12.pp \
./fonts/fontcmsc14.pp \
./fonts/fontcmsc16.pp \
./fonts/fontcmsc18.pp \
./fonts/fontcmsc20.pp \
./fonts/fontcmsc22.pp \
./fonts/fontcmsc24.pp \
./fonts/fontcmsc26.pp \
./fonts/fontcmsc28.pp \
./fonts/fontcmsc30.pp \
./fonts/fontcmsc32.pp \
./fonts/fontcmsc34.pp \
./fonts/fontcmsc36.pp \
./fonts/fontcmsc38.pp \
./fonts/fontcmsc40.pp \
./fonts/fontcmsc42.pp \
./fonts/fontcmsc44.pp \
./fonts/fontcmsc46.pp \
./fonts/fontcmsc48.pp \
./fonts/fontcmss12.pp \
./fonts/fontcmss12b.pp \
./fonts/fontcmss12i.pp \
./fonts/fontcmss14.pp \
./fonts/fontcmss14b.pp \
./fonts/fontcmss14i.pp \
./fonts/fontcmss16.pp \
./fonts/fontcmss16b.pp \
./fonts/fontcmss16i.pp \
./fonts/fontcmss18.pp \
./fonts/fontcmss18b.pp \
./fonts/fontcmss18i.pp \
./fonts/fontcmss20.pp \
./fonts/fontcmss20b.pp \
./fonts/fontcmss20i.pp \
./fonts/fontcmss22.pp \
./fonts/fontcmss22b.pp \
./fonts/fontcmss22i.pp \
./fonts/fontcmss24.pp \
./fonts/fontcmss24b.pp \
./fonts/fontcmss24i.pp \
./fonts/fontcmss26.pp \
./fonts/fontcmss26b.pp \
./fonts/fontcmss26i.pp \
./fonts/fontcmss28.pp \
./fonts/fontcmss28b.pp \
./fonts/fontcmss28i.pp \
./fonts/fontcmss30.pp \
./fonts/fontcmss30b.pp \
./fonts/fontcmss30i.pp \
./fonts/fontcmss32.pp \
./fonts/fontcmss32b.pp \
./fonts/fontcmss32i.pp \
./fonts/fontcmss34.pp \
./fonts/fontcmss34b.pp \
./fonts/fontcmss34i.pp \
./fonts/fontcmss36.pp \
./fonts/fontcmss36b.pp \
./fonts/fontcmss36i.pp \
./fonts/fontcmss38.pp \
./fonts/fontcmss38b.pp \
./fonts/fontcmss38i.pp \
./fonts/fontcmss40.pp \
./fonts/fontcmss40b.pp \
./fonts/fontcmss40i.pp \
./fonts/fontcmss42.pp \
./fonts/fontcmss42b.pp \
./fonts/fontcmss42i.pp \
./fonts/fontcmss44.pp \
./fonts/fontcmss44b.pp \
./fonts/fontcmss44i.pp \
./fonts/fontcmss46.pp \
./fonts/fontcmss46b.pp \
./fonts/fontcmss46i.pp \
./fonts/fontcmss48.pp \
./fonts/fontcmss48b.pp \
./fonts/fontcmss48i.pp \
./fonts/fontcmtt12.pp \
./fonts/fontcmtt14.pp \
./fonts/fontcmtt16.pp \
./fonts/fontcmtt18.pp \
./fonts/fontcmtt20.pp \
./fonts/fontcmtt22.pp \
./fonts/fontcmtt24.pp \
./fonts/fontcmtt26.pp \
./fonts/fontcmtt28.pp \
./fonts/fontcmtt30.pp \
./fonts/fontcmtt32.pp \
./fonts/fontcmtt34.pp \
./fonts/fontcmtt36.pp \
./fonts/fontcmtt38.pp \
./fonts/fontcmtt40.pp \
./fonts/fontcmtt42.pp \
./fonts/fontcmtt44.pp \
./fonts/fontcmtt46.pp \
./fonts/fontcmtt48.pp \
./fonts/fontfixed6x8.pp 

C_DEPS__QUOTED += \
"fonts\fontcm12.pp" \
"fonts\fontcm12b.pp" \
"fonts\fontcm12i.pp" \
"fonts\fontcm14.pp" \
"fonts\fontcm14b.pp" \
"fonts\fontcm14i.pp" \
"fonts\fontcm16.pp" \
"fonts\fontcm16b.pp" \
"fonts\fontcm16i.pp" \
"fonts\fontcm18.pp" \
"fonts\fontcm18b.pp" \
"fonts\fontcm18i.pp" \
"fonts\fontcm20.pp" \
"fonts\fontcm20b.pp" \
"fonts\fontcm20i.pp" \
"fonts\fontcm22.pp" \
"fonts\fontcm22b.pp" \
"fonts\fontcm22i.pp" \
"fonts\fontcm24.pp" \
"fonts\fontcm24b.pp" \
"fonts\fontcm24i.pp" \
"fonts\fontcm26.pp" \
"fonts\fontcm26b.pp" \
"fonts\fontcm26i.pp" \
"fonts\fontcm28.pp" \
"fonts\fontcm28b.pp" \
"fonts\fontcm28i.pp" \
"fonts\fontcm30.pp" \
"fonts\fontcm30b.pp" \
"fonts\fontcm30i.pp" \
"fonts\fontcm32.pp" \
"fonts\fontcm32b.pp" \
"fonts\fontcm32i.pp" \
"fonts\fontcm34.pp" \
"fonts\fontcm34b.pp" \
"fonts\fontcm34i.pp" \
"fonts\fontcm36.pp" \
"fonts\fontcm36b.pp" \
"fonts\fontcm36i.pp" \
"fonts\fontcm38.pp" \
"fonts\fontcm38b.pp" \
"fonts\fontcm38i.pp" \
"fonts\fontcm40.pp" \
"fonts\fontcm40b.pp" \
"fonts\fontcm40i.pp" \
"fonts\fontcm42.pp" \
"fonts\fontcm42b.pp" \
"fonts\fontcm42i.pp" \
"fonts\fontcm44.pp" \
"fonts\fontcm44b.pp" \
"fonts\fontcm44i.pp" \
"fonts\fontcm46.pp" \
"fonts\fontcm46b.pp" \
"fonts\fontcm46i.pp" \
"fonts\fontcm48.pp" \
"fonts\fontcm48b.pp" \
"fonts\fontcm48i.pp" \
"fonts\fontcmsc12.pp" \
"fonts\fontcmsc14.pp" \
"fonts\fontcmsc16.pp" \
"fonts\fontcmsc18.pp" \
"fonts\fontcmsc20.pp" \
"fonts\fontcmsc22.pp" \
"fonts\fontcmsc24.pp" \
"fonts\fontcmsc26.pp" \
"fonts\fontcmsc28.pp" \
"fonts\fontcmsc30.pp" \
"fonts\fontcmsc32.pp" \
"fonts\fontcmsc34.pp" \
"fonts\fontcmsc36.pp" \
"fonts\fontcmsc38.pp" \
"fonts\fontcmsc40.pp" \
"fonts\fontcmsc42.pp" \
"fonts\fontcmsc44.pp" \
"fonts\fontcmsc46.pp" \
"fonts\fontcmsc48.pp" \
"fonts\fontcmss12.pp" \
"fonts\fontcmss12b.pp" \
"fonts\fontcmss12i.pp" \
"fonts\fontcmss14.pp" \
"fonts\fontcmss14b.pp" \
"fonts\fontcmss14i.pp" \
"fonts\fontcmss16.pp" \
"fonts\fontcmss16b.pp" \
"fonts\fontcmss16i.pp" \
"fonts\fontcmss18.pp" \
"fonts\fontcmss18b.pp" \
"fonts\fontcmss18i.pp" \
"fonts\fontcmss20.pp" \
"fonts\fontcmss20b.pp" \
"fonts\fontcmss20i.pp" \
"fonts\fontcmss22.pp" \
"fonts\fontcmss22b.pp" \
"fonts\fontcmss22i.pp" \
"fonts\fontcmss24.pp" \
"fonts\fontcmss24b.pp" \
"fonts\fontcmss24i.pp" \
"fonts\fontcmss26.pp" \
"fonts\fontcmss26b.pp" \
"fonts\fontcmss26i.pp" \
"fonts\fontcmss28.pp" \
"fonts\fontcmss28b.pp" \
"fonts\fontcmss28i.pp" \
"fonts\fontcmss30.pp" \
"fonts\fontcmss30b.pp" \
"fonts\fontcmss30i.pp" \
"fonts\fontcmss32.pp" \
"fonts\fontcmss32b.pp" \
"fonts\fontcmss32i.pp" \
"fonts\fontcmss34.pp" \
"fonts\fontcmss34b.pp" \
"fonts\fontcmss34i.pp" \
"fonts\fontcmss36.pp" \
"fonts\fontcmss36b.pp" \
"fonts\fontcmss36i.pp" \
"fonts\fontcmss38.pp" \
"fonts\fontcmss38b.pp" \
"fonts\fontcmss38i.pp" \
"fonts\fontcmss40.pp" \
"fonts\fontcmss40b.pp" \
"fonts\fontcmss40i.pp" \
"fonts\fontcmss42.pp" \
"fonts\fontcmss42b.pp" \
"fonts\fontcmss42i.pp" \
"fonts\fontcmss44.pp" \
"fonts\fontcmss44b.pp" \
"fonts\fontcmss44i.pp" \
"fonts\fontcmss46.pp" \
"fonts\fontcmss46b.pp" \
"fonts\fontcmss46i.pp" \
"fonts\fontcmss48.pp" \
"fonts\fontcmss48b.pp" \
"fonts\fontcmss48i.pp" \
"fonts\fontcmtt12.pp" \
"fonts\fontcmtt14.pp" \
"fonts\fontcmtt16.pp" \
"fonts\fontcmtt18.pp" \
"fonts\fontcmtt20.pp" \
"fonts\fontcmtt22.pp" \
"fonts\fontcmtt24.pp" \
"fonts\fontcmtt26.pp" \
"fonts\fontcmtt28.pp" \
"fonts\fontcmtt30.pp" \
"fonts\fontcmtt32.pp" \
"fonts\fontcmtt34.pp" \
"fonts\fontcmtt36.pp" \
"fonts\fontcmtt38.pp" \
"fonts\fontcmtt40.pp" \
"fonts\fontcmtt42.pp" \
"fonts\fontcmtt44.pp" \
"fonts\fontcmtt46.pp" \
"fonts\fontcmtt48.pp" \
"fonts\fontfixed6x8.pp" 

OBJS__QUOTED += \
"fonts\fontcm12.obj" \
"fonts\fontcm12b.obj" \
"fonts\fontcm12i.obj" \
"fonts\fontcm14.obj" \
"fonts\fontcm14b.obj" \
"fonts\fontcm14i.obj" \
"fonts\fontcm16.obj" \
"fonts\fontcm16b.obj" \
"fonts\fontcm16i.obj" \
"fonts\fontcm18.obj" \
"fonts\fontcm18b.obj" \
"fonts\fontcm18i.obj" \
"fonts\fontcm20.obj" \
"fonts\fontcm20b.obj" \
"fonts\fontcm20i.obj" \
"fonts\fontcm22.obj" \
"fonts\fontcm22b.obj" \
"fonts\fontcm22i.obj" \
"fonts\fontcm24.obj" \
"fonts\fontcm24b.obj" \
"fonts\fontcm24i.obj" \
"fonts\fontcm26.obj" \
"fonts\fontcm26b.obj" \
"fonts\fontcm26i.obj" \
"fonts\fontcm28.obj" \
"fonts\fontcm28b.obj" \
"fonts\fontcm28i.obj" \
"fonts\fontcm30.obj" \
"fonts\fontcm30b.obj" \
"fonts\fontcm30i.obj" \
"fonts\fontcm32.obj" \
"fonts\fontcm32b.obj" \
"fonts\fontcm32i.obj" \
"fonts\fontcm34.obj" \
"fonts\fontcm34b.obj" \
"fonts\fontcm34i.obj" \
"fonts\fontcm36.obj" \
"fonts\fontcm36b.obj" \
"fonts\fontcm36i.obj" \
"fonts\fontcm38.obj" \
"fonts\fontcm38b.obj" \
"fonts\fontcm38i.obj" \
"fonts\fontcm40.obj" \
"fonts\fontcm40b.obj" \
"fonts\fontcm40i.obj" \
"fonts\fontcm42.obj" \
"fonts\fontcm42b.obj" \
"fonts\fontcm42i.obj" \
"fonts\fontcm44.obj" \
"fonts\fontcm44b.obj" \
"fonts\fontcm44i.obj" \
"fonts\fontcm46.obj" \
"fonts\fontcm46b.obj" \
"fonts\fontcm46i.obj" \
"fonts\fontcm48.obj" \
"fonts\fontcm48b.obj" \
"fonts\fontcm48i.obj" \
"fonts\fontcmsc12.obj" \
"fonts\fontcmsc14.obj" \
"fonts\fontcmsc16.obj" \
"fonts\fontcmsc18.obj" \
"fonts\fontcmsc20.obj" \
"fonts\fontcmsc22.obj" \
"fonts\fontcmsc24.obj" \
"fonts\fontcmsc26.obj" \
"fonts\fontcmsc28.obj" \
"fonts\fontcmsc30.obj" \
"fonts\fontcmsc32.obj" \
"fonts\fontcmsc34.obj" \
"fonts\fontcmsc36.obj" \
"fonts\fontcmsc38.obj" \
"fonts\fontcmsc40.obj" \
"fonts\fontcmsc42.obj" \
"fonts\fontcmsc44.obj" \
"fonts\fontcmsc46.obj" \
"fonts\fontcmsc48.obj" \
"fonts\fontcmss12.obj" \
"fonts\fontcmss12b.obj" \
"fonts\fontcmss12i.obj" \
"fonts\fontcmss14.obj" \
"fonts\fontcmss14b.obj" \
"fonts\fontcmss14i.obj" \
"fonts\fontcmss16.obj" \
"fonts\fontcmss16b.obj" \
"fonts\fontcmss16i.obj" \
"fonts\fontcmss18.obj" \
"fonts\fontcmss18b.obj" \
"fonts\fontcmss18i.obj" \
"fonts\fontcmss20.obj" \
"fonts\fontcmss20b.obj" \
"fonts\fontcmss20i.obj" \
"fonts\fontcmss22.obj" \
"fonts\fontcmss22b.obj" \
"fonts\fontcmss22i.obj" \
"fonts\fontcmss24.obj" \
"fonts\fontcmss24b.obj" \
"fonts\fontcmss24i.obj" \
"fonts\fontcmss26.obj" \
"fonts\fontcmss26b.obj" \
"fonts\fontcmss26i.obj" \
"fonts\fontcmss28.obj" \
"fonts\fontcmss28b.obj" \
"fonts\fontcmss28i.obj" \
"fonts\fontcmss30.obj" \
"fonts\fontcmss30b.obj" \
"fonts\fontcmss30i.obj" \
"fonts\fontcmss32.obj" \
"fonts\fontcmss32b.obj" \
"fonts\fontcmss32i.obj" \
"fonts\fontcmss34.obj" \
"fonts\fontcmss34b.obj" \
"fonts\fontcmss34i.obj" \
"fonts\fontcmss36.obj" \
"fonts\fontcmss36b.obj" \
"fonts\fontcmss36i.obj" \
"fonts\fontcmss38.obj" \
"fonts\fontcmss38b.obj" \
"fonts\fontcmss38i.obj" \
"fonts\fontcmss40.obj" \
"fonts\fontcmss40b.obj" \
"fonts\fontcmss40i.obj" \
"fonts\fontcmss42.obj" \
"fonts\fontcmss42b.obj" \
"fonts\fontcmss42i.obj" \
"fonts\fontcmss44.obj" \
"fonts\fontcmss44b.obj" \
"fonts\fontcmss44i.obj" \
"fonts\fontcmss46.obj" \
"fonts\fontcmss46b.obj" \
"fonts\fontcmss46i.obj" \
"fonts\fontcmss48.obj" \
"fonts\fontcmss48b.obj" \
"fonts\fontcmss48i.obj" \
"fonts\fontcmtt12.obj" \
"fonts\fontcmtt14.obj" \
"fonts\fontcmtt16.obj" \
"fonts\fontcmtt18.obj" \
"fonts\fontcmtt20.obj" \
"fonts\fontcmtt22.obj" \
"fonts\fontcmtt24.obj" \
"fonts\fontcmtt26.obj" \
"fonts\fontcmtt28.obj" \
"fonts\fontcmtt30.obj" \
"fonts\fontcmtt32.obj" \
"fonts\fontcmtt34.obj" \
"fonts\fontcmtt36.obj" \
"fonts\fontcmtt38.obj" \
"fonts\fontcmtt40.obj" \
"fonts\fontcmtt42.obj" \
"fonts\fontcmtt44.obj" \
"fonts\fontcmtt46.obj" \
"fonts\fontcmtt48.obj" \
"fonts\fontfixed6x8.obj" 

C_SRCS__QUOTED += \
"../fonts/fontcm12.c" \
"../fonts/fontcm12b.c" \
"../fonts/fontcm12i.c" \
"../fonts/fontcm14.c" \
"../fonts/fontcm14b.c" \
"../fonts/fontcm14i.c" \
"../fonts/fontcm16.c" \
"../fonts/fontcm16b.c" \
"../fonts/fontcm16i.c" \
"../fonts/fontcm18.c" \
"../fonts/fontcm18b.c" \
"../fonts/fontcm18i.c" \
"../fonts/fontcm20.c" \
"../fonts/fontcm20b.c" \
"../fonts/fontcm20i.c" \
"../fonts/fontcm22.c" \
"../fonts/fontcm22b.c" \
"../fonts/fontcm22i.c" \
"../fonts/fontcm24.c" \
"../fonts/fontcm24b.c" \
"../fonts/fontcm24i.c" \
"../fonts/fontcm26.c" \
"../fonts/fontcm26b.c" \
"../fonts/fontcm26i.c" \
"../fonts/fontcm28.c" \
"../fonts/fontcm28b.c" \
"../fonts/fontcm28i.c" \
"../fonts/fontcm30.c" \
"../fonts/fontcm30b.c" \
"../fonts/fontcm30i.c" \
"../fonts/fontcm32.c" \
"../fonts/fontcm32b.c" \
"../fonts/fontcm32i.c" \
"../fonts/fontcm34.c" \
"../fonts/fontcm34b.c" \
"../fonts/fontcm34i.c" \
"../fonts/fontcm36.c" \
"../fonts/fontcm36b.c" \
"../fonts/fontcm36i.c" \
"../fonts/fontcm38.c" \
"../fonts/fontcm38b.c" \
"../fonts/fontcm38i.c" \
"../fonts/fontcm40.c" \
"../fonts/fontcm40b.c" \
"../fonts/fontcm40i.c" \
"../fonts/fontcm42.c" \
"../fonts/fontcm42b.c" \
"../fonts/fontcm42i.c" \
"../fonts/fontcm44.c" \
"../fonts/fontcm44b.c" \
"../fonts/fontcm44i.c" \
"../fonts/fontcm46.c" \
"../fonts/fontcm46b.c" \
"../fonts/fontcm46i.c" \
"../fonts/fontcm48.c" \
"../fonts/fontcm48b.c" \
"../fonts/fontcm48i.c" \
"../fonts/fontcmsc12.c" \
"../fonts/fontcmsc14.c" \
"../fonts/fontcmsc16.c" \
"../fonts/fontcmsc18.c" \
"../fonts/fontcmsc20.c" \
"../fonts/fontcmsc22.c" \
"../fonts/fontcmsc24.c" \
"../fonts/fontcmsc26.c" \
"../fonts/fontcmsc28.c" \
"../fonts/fontcmsc30.c" \
"../fonts/fontcmsc32.c" \
"../fonts/fontcmsc34.c" \
"../fonts/fontcmsc36.c" \
"../fonts/fontcmsc38.c" \
"../fonts/fontcmsc40.c" \
"../fonts/fontcmsc42.c" \
"../fonts/fontcmsc44.c" \
"../fonts/fontcmsc46.c" \
"../fonts/fontcmsc48.c" \
"../fonts/fontcmss12.c" \
"../fonts/fontcmss12b.c" \
"../fonts/fontcmss12i.c" \
"../fonts/fontcmss14.c" \
"../fonts/fontcmss14b.c" \
"../fonts/fontcmss14i.c" \
"../fonts/fontcmss16.c" \
"../fonts/fontcmss16b.c" \
"../fonts/fontcmss16i.c" \
"../fonts/fontcmss18.c" \
"../fonts/fontcmss18b.c" \
"../fonts/fontcmss18i.c" \
"../fonts/fontcmss20.c" \
"../fonts/fontcmss20b.c" \
"../fonts/fontcmss20i.c" \
"../fonts/fontcmss22.c" \
"../fonts/fontcmss22b.c" \
"../fonts/fontcmss22i.c" \
"../fonts/fontcmss24.c" \
"../fonts/fontcmss24b.c" \
"../fonts/fontcmss24i.c" \
"../fonts/fontcmss26.c" \
"../fonts/fontcmss26b.c" \
"../fonts/fontcmss26i.c" \
"../fonts/fontcmss28.c" \
"../fonts/fontcmss28b.c" \
"../fonts/fontcmss28i.c" \
"../fonts/fontcmss30.c" \
"../fonts/fontcmss30b.c" \
"../fonts/fontcmss30i.c" \
"../fonts/fontcmss32.c" \
"../fonts/fontcmss32b.c" \
"../fonts/fontcmss32i.c" \
"../fonts/fontcmss34.c" \
"../fonts/fontcmss34b.c" \
"../fonts/fontcmss34i.c" \
"../fonts/fontcmss36.c" \
"../fonts/fontcmss36b.c" \
"../fonts/fontcmss36i.c" \
"../fonts/fontcmss38.c" \
"../fonts/fontcmss38b.c" \
"../fonts/fontcmss38i.c" \
"../fonts/fontcmss40.c" \
"../fonts/fontcmss40b.c" \
"../fonts/fontcmss40i.c" \
"../fonts/fontcmss42.c" \
"../fonts/fontcmss42b.c" \
"../fonts/fontcmss42i.c" \
"../fonts/fontcmss44.c" \
"../fonts/fontcmss44b.c" \
"../fonts/fontcmss44i.c" \
"../fonts/fontcmss46.c" \
"../fonts/fontcmss46b.c" \
"../fonts/fontcmss46i.c" \
"../fonts/fontcmss48.c" \
"../fonts/fontcmss48b.c" \
"../fonts/fontcmss48i.c" \
"../fonts/fontcmtt12.c" \
"../fonts/fontcmtt14.c" \
"../fonts/fontcmtt16.c" \
"../fonts/fontcmtt18.c" \
"../fonts/fontcmtt20.c" \
"../fonts/fontcmtt22.c" \
"../fonts/fontcmtt24.c" \
"../fonts/fontcmtt26.c" \
"../fonts/fontcmtt28.c" \
"../fonts/fontcmtt30.c" \
"../fonts/fontcmtt32.c" \
"../fonts/fontcmtt34.c" \
"../fonts/fontcmtt36.c" \
"../fonts/fontcmtt38.c" \
"../fonts/fontcmtt40.c" \
"../fonts/fontcmtt42.c" \
"../fonts/fontcmtt44.c" \
"../fonts/fontcmtt46.c" \
"../fonts/fontcmtt48.c" \
"../fonts/fontfixed6x8.c" 


