/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_3_00_03_66/packages/ti/mcu/msp430/csl2/rtc/RTC_B_init.xdt
 */
#include <driverlib/MSP430FR5xx_6xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR5xx_6xx/rtc_b.h>
#include "_Grace.h"

/* USER CODE START (section: RTC_B_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: RTC_B_init_c_prologue) */

/*
 *  ======== RTC_B_graceInit ========
 *  Initialize Config for the MSP430 RTC_B
 */
void RTC_B_graceInit(void)
{
    /* Struct to pass to RTC_B_CalendarInit() */
    Calendar calendarTime;

    /* USER CODE START (section: RTC_B_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: RTC_B_graceInit_prologue) */

    /* Initialize the Calendar struct */
    calendarTime.Seconds = 0;
    calendarTime.Minutes = 0;
    calendarTime.Hours = 12;
    calendarTime.DayOfWeek = 3;
    calendarTime.DayOfMonth = 5;
    calendarTime.Month = 8;
    calendarTime.Year = 2015;

    /* Initialize the settings to operate the RTC in Calendar mode */
    RTC_B_calendarInit(RTC_B_BASE, calendarTime, RTC_B_FORMAT_BCD);

    /* Set and enable the desired Calendar Alarm settings */
    RTC_B_setCalendarAlarm(RTC_B_BASE,
                           RTC_B_ALARMCONDITION_OFF, /* minutes */
                           RTC_B_ALARMCONDITION_OFF, /* hours */
                           RTC_B_ALARMCONDITION_OFF, /* day of the week */
                           RTC_B_ALARMCONDITION_OFF  /* day of the month */
    );

    /* Set a single specified Calendar interrupt condition */
    RTC_B_setCalendarEvent(RTC_B_BASE, RTC_B_CALENDAREVENT_MINUTECHANGE);

    /* Hold the RTC */
    RTC_B_holdClock(RTC_B_BASE);

    /* USER CODE START (section: RTC_B_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: RTC_B_graceInit_epilogue) */
}

